name: Publish package to the Maven Central Repository
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y-SNAPSHOT"
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: install-secret-key 
        name: Install gpg secret key 
        run: | 
          # Install gpg secret key 
          cat <(echo -e "${{ secrets.GPG_SIGNING_KEY }}") | gpg --batch --import 
          # Verify gpg secret key 
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@v3
        with:
          ref: main
        env:
          branch: main
          working_directory: ./code/
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn -Prelease --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} deploy -f ./code/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
