name: Test Action
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y-SNAPSHOT"
permissions:
  contents: write
jobs:
  testRun:
    runs-on: ubuntu-latest
    steps:
      - id: install-secret-key 
        name: Install gpg secret key 
        run: | 
          # Install gpg secret key 
          cat <(echo -e "${{ secrets.GPG_SIGNING_KEY }}") | gpg --batch --import 
          # Verify gpg secret key 
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@v3
        with:
          ref: main
        env:
          branch: main
          working_directory: ./code/
      - name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }} -DgenerateBackupPoms=false -f ./code/pom.xml
      - name: Commit report
        run: |
          git config --global user.name ${{ secrets.GH_USERNAME }}
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git commit -am "Version updated to ${{ github.event.inputs.releaseVersion }}"
          git push
      #- uses: stefanzweifel/git-auto-commit-action@v5
      #  with:
      #    commit_message: Version updated to ${{ github.event.inputs.releaseVersion }}
