name: Test Action
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y-SNAPSHOT"
jobs:
  testRun:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: install-secret-key 
        name: Install gpg secret key 
        run: | 
          # Install gpg secret key 
          cat <(echo -e "${{ secrets.GPG_SIGNING_KEY }}") | gpg --batch --import 
          # Verify gpg secret key 
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@v3
        with:
          ref: main
        env:
          branch: main
          working_directory: ./code/
      - name: Update version in pom.xml
        run: mvn -B versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }} -DgenerateBackupPoms=false -f ./code/pom.xml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version updated to ${{ github.event.inputs.releaseVersion }}
